{"uuid":"46bc8860-23b0-4ed2-85ad-a046bb02b805","historyId":"c19b73d14bf9fbf05d1cbcbc4e79e869","fullName":"base.BaseTest.staringServer","labels":[{"name":"package","value":"tests.PurplleTest"},{"name":"testClass","value":"tests.PurplleTest"},{"name":"testMethod","value":"staringServer"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Purplle"},{"name":"subSuite","value":"tests.PurplleTest"},{"name":"host","value":"Naziyas-MacBook-Pro.local"},{"name":"thread","value":"40705@Naziyas-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"staringServer","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The local appium server has not been started. The given Node.js executable: /Users/naziya/.nvm/versions/node/v16.14.0/bin/node Arguments: [/Users/naziya/.nvm/versions/node/v16.14.0/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0, --log, /Users/naziya/Documents/Automation/Purplle/./logs/appiumLogs.txt] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\n\u001B[35m[Appium]\u001B[39m Non-default server args:\n\u001B[35m[Appium]\u001B[39m   logFile: /Users/naziya/Documents/Automation/Purplle/./logs/appiumLogs.txt\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\nFatal Error: listen EADDRINUSE: address already in use 0.0.0.0:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1330:16)\n    at listenInCluster (node:net:1378:12)\n    at doListen (node:net:1516:7)\n    at processTicksAndRejections (node:internal/process/task_queues:84:21)\n\n","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: /Users/naziya/.nvm/versions/node/v16.14.0/bin/node Arguments: [/Users/naziya/.nvm/versions/node/v16.14.0/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0, --log, /Users/naziya/Documents/Automation/Purplle/./logs/appiumLogs.txt] \nProcess output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v1.22.3\n\u001B[35m[Appium]\u001B[39m Non-default server args:\n\u001B[35m[Appium]\u001B[39m   logFile: /Users/naziya/Documents/Automation/Purplle/./logs/appiumLogs.txt\n\u001B[35m[HTTP]\u001B[39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\nFatal Error: listen EADDRINUSE: address already in use 0.0.0.0:4723\n    at Server.setupListenHandle [as _listen2] (node:net:1330:16)\n    at listenInCluster (node:net:1378:12)\n    at doListen (node:net:1516:7)\n    at processTicksAndRejections (node:internal/process/task_queues:84:21)\n\n\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:164)\n\tat capabilities.DesiredCapabilitiesBuilder.startServer(DesiredCapabilitiesBuilder.java:72)\n\tat base.BaseTest.staringServer(BaseTest.java:22)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\n\tat org.testng.TestNG.run(TestNG.java:1037)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/wd/hub/status] to be available after 120009 ms\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:129)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:151)\n\t... 20 more\nCaused by: java.util.concurrent.TimeoutException\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:205)\n\tat com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)\n\t... 22 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1671519609461,"stop":1671519609465}